import Head from 'next/head';
import { CSubHeader } from '~/common/components/layout';
import { CConsultation, CDoctor } from '~/common/components/other';
import { Experiment, Certificates } from '~/modules/About';

const About = () => {
	return (
		<>
			<Head>
				<title>Contact</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<CSubHeader title="About us" />

			<section>
				<CDoctor />
			</section>

			<Experiment />

			<Certificates />

			<section>
				<CConsultation />
			</section>
		</>
	);
};

export default About;
