import Head from 'next/head';
import { ContactHeader, ContactInfo, RegisterCare } from '~/modules/Contact';

const Contact = () => {
	return (
		<>
			<Head>
				<title>Contact</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<ContactHeader />

			<ContactInfo />

			<RegisterCare />
		</>
	);
};

export default Contact;
