import Head from 'next/head';
import { CDoctor } from '~/common/components/other';
import {
	Consultation,
	Doctor,
	Intro,
	Offering,
	Plans,
	Questions,
	Rating,
} from '~/modules/Home';

export default function Home() {
	return (
		<>
			<Head>
				<title>Talking Minds</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<section>
				<Intro />
			</section>

			<Offering />

			<section>
				<CDoctor />
			</section>

			<Plans />

			<section>
				<Rating />
			</section>

			<section className="py-0">
				<Consultation />
			</section>

			<Questions />
		</>
	);
}
