import Head from 'next/head';
import {
	Consultation,
	Doctor,
	Intro,
	Offering,
	Plans,
	Rating,
} from '~/modules/Home';

export default function Home() {
	return (
		<>
			<Head>
				<title>Talking Minds</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<section>
				<Intro />
			</section>

			<Offering />

			<section>
				<Doctor />
			</section>

			<Plans />

			<section>
				<Rating />
			</section>

			<section>
				<Consultation />
			</section>
		</>
	);
}
