import Head from 'next/head';
import { CSubHeader } from '~/common/components/layout';
import { HealthPrograms, Plans, Process } from '~/modules/Program';

const Program = () => {
	return (
		<>
			<Head>
				<title>Program</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<CSubHeader title="All programs" />

			<HealthPrograms />

			<Process />

			<Plans />
		</>
	);
};

export default Program;
